name: flutter_myapp_assets
description: Images and fonts for the Flutter gallery demo
version: 0.0.26
author: Flutter Authors <flutter-dev@googlegroups.com>
homepage: http://flutter.io

environment:
  sdk: ">2.0.0 <=2.1.0"
